// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: login.proto

package loginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_GetBearer_FullMethodName = "/login.LoginService/GetBearer"
	LoginService_Health_FullMethodName    = "/login.LoginService/Health"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LoginService returns a valid jus.br bearer token with session reuse.
// A headless login runs only when no fresh cached token is available
// (or force=true). Concurrent GetBearer calls coalesce into a single login.
//
// SECURITY: transport is plain TCP by default, acceptable only on loopback
// or a trusted LAN segment - identical posture to SignerService (signer.proto).
// The bearer returned is a credential.  Do NOT expose this port on an
// untrusted network without TLS.  mTLS hardening is tracked as a backlog item.
type LoginServiceClient interface {
	// GetBearer returns a valid bearer, performing a headless login only if no
	// fresh cached token exists (or force=true). Concurrent calls coalesce into a
	// single login.
	GetBearer(ctx context.Context, in *GetBearerRequest, opts ...grpc.CallOption) (*BearerReply, error)
	// Health reports liveness and whether a (non-expired) bearer is cached.
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) GetBearer(ctx context.Context, in *GetBearerRequest, opts ...grpc.CallOption) (*BearerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BearerReply)
	err := c.cc.Invoke(ctx, LoginService_GetBearer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, LoginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
//
// LoginService returns a valid jus.br bearer token with session reuse.
// A headless login runs only when no fresh cached token is available
// (or force=true). Concurrent GetBearer calls coalesce into a single login.
//
// SECURITY: transport is plain TCP by default, acceptable only on loopback
// or a trusted LAN segment - identical posture to SignerService (signer.proto).
// The bearer returned is a credential.  Do NOT expose this port on an
// untrusted network without TLS.  mTLS hardening is tracked as a backlog item.
type LoginServiceServer interface {
	// GetBearer returns a valid bearer, performing a headless login only if no
	// fresh cached token exists (or force=true). Concurrent calls coalesce into a
	// single login.
	GetBearer(context.Context, *GetBearerRequest) (*BearerReply, error)
	// Health reports liveness and whether a (non-expired) bearer is cached.
	Health(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) GetBearer(context.Context, *GetBearerRequest) (*BearerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBearer not implemented")
}
func (UnimplementedLoginServiceServer) Health(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_GetBearer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBearerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetBearer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_GetBearer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetBearer(ctx, req.(*GetBearerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "login.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBearer",
			Handler:    _LoginService_GetBearer_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LoginService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
