// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: signer.proto

package signerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{0}
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *SignRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type SignReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignatureB64  string                 `protobuf:"bytes,1,opt,name=signature_b64,json=signatureB64,proto3" json:"signature_b64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignReply) Reset() {
	*x = SignReply{}
	mi := &file_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReply) ProtoMessage() {}

func (x *SignReply) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReply.ProtoReflect.Descriptor instead.
func (*SignReply) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{2}
}

func (x *SignReply) GetSignatureB64() string {
	if x != nil {
		return x.SignatureB64
	}
	return ""
}

type Chain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkipathB64    string                 `protobuf:"bytes,1,opt,name=pkipath_b64,json=pkipathB64,proto3" json:"pkipath_b64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{3}
}

func (x *Chain) GetPkipathB64() string {
	if x != nil {
		return x.PkipathB64
	}
	return ""
}

type IdentityMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	NotAfterUnix  int64                  `protobuf:"varint,4,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityMsg) Reset() {
	*x = IdentityMsg{}
	mi := &file_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityMsg) ProtoMessage() {}

func (x *IdentityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityMsg.ProtoReflect.Descriptor instead.
func (*IdentityMsg) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityMsg) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IdentityMsg) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentityMsg) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *IdentityMsg) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

type HealthStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ready           bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	IdentitySubject string                 `protobuf:"bytes,2,opt,name=identity_subject,json=identitySubject,proto3" json:"identity_subject,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_signer_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthStatus) GetIdentitySubject() string {
	if x != nil {
		return x.IdentitySubject
	}
	return ""
}

var File_signer_proto protoreflect.FileDescriptor

const file_signer_proto_rawDesc = "" +
	"\n" +
	"\fsigner.proto\x12\x06signer\"\a\n" +
	"\x05Empty\"C\n" +
	"\vSignRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"0\n" +
	"\tSignReply\x12#\n" +
	"\rsignature_b64\x18\x01 \x01(\tR\fsignatureB64\"(\n" +
	"\x05Chain\x12\x1f\n" +
	"\vpkipath_b64\x18\x01 \x01(\tR\n" +
	"pkipathB64\"}\n" +
	"\vIdentityMsg\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12$\n" +
	"\x0enot_after_unix\x18\x04 \x01(\x03R\fnotAfterUnix\"O\n" +
	"\fHealthStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12)\n" +
	"\x10identity_subject\x18\x02 \x01(\tR\x0fidentitySubject2\xd0\x01\n" +
	"\rSignerService\x12.\n" +
	"\x04Sign\x12\x13.signer.SignRequest\x1a\x11.signer.SignReply\x120\n" +
	"\x10CertChainPKIPath\x12\r.signer.Empty\x1a\r.signer.Chain\x12.\n" +
	"\bIdentity\x12\r.signer.Empty\x1a\x13.signer.IdentityMsg\x12-\n" +
	"\x06Health\x12\r.signer.Empty\x1a\x14.signer.HealthStatusB:Z8github.com/MrSchrodingers/pje_headless/internal/signerpbb\x06proto3"

var (
	file_signer_proto_rawDescOnce sync.Once
	file_signer_proto_rawDescData []byte
)

func file_signer_proto_rawDescGZIP() []byte {
	file_signer_proto_rawDescOnce.Do(func() {
		file_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)))
	})
	return file_signer_proto_rawDescData
}

var file_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_signer_proto_goTypes = []any{
	(*Empty)(nil),        // 0: signer.Empty
	(*SignRequest)(nil),  // 1: signer.SignRequest
	(*SignReply)(nil),    // 2: signer.SignReply
	(*Chain)(nil),        // 3: signer.Chain
	(*IdentityMsg)(nil),  // 4: signer.IdentityMsg
	(*HealthStatus)(nil), // 5: signer.HealthStatus
}
var file_signer_proto_depIdxs = []int32{
	1, // 0: signer.SignerService.Sign:input_type -> signer.SignRequest
	0, // 1: signer.SignerService.CertChainPKIPath:input_type -> signer.Empty
	0, // 2: signer.SignerService.Identity:input_type -> signer.Empty
	0, // 3: signer.SignerService.Health:input_type -> signer.Empty
	2, // 4: signer.SignerService.Sign:output_type -> signer.SignReply
	3, // 5: signer.SignerService.CertChainPKIPath:output_type -> signer.Chain
	4, // 6: signer.SignerService.Identity:output_type -> signer.IdentityMsg
	5, // 7: signer.SignerService.Health:output_type -> signer.HealthStatus
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signer_proto_init() }
func file_signer_proto_init() {
	if File_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signer_proto_rawDesc), len(file_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signer_proto_goTypes,
		DependencyIndexes: file_signer_proto_depIdxs,
		MessageInfos:      file_signer_proto_msgTypes,
	}.Build()
	File_signer_proto = out.File
	file_signer_proto_goTypes = nil
	file_signer_proto_depIdxs = nil
}
