// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: signer.proto

package signerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignerService_Sign_FullMethodName             = "/signer.SignerService/Sign"
	SignerService_CertChainPKIPath_FullMethodName = "/signer.SignerService/CertChainPKIPath"
	SignerService_Identity_FullMethodName         = "/signer.SignerService/Identity"
	SignerService_Health_FullMethodName           = "/signer.SignerService/Health"
)

// SignerServiceClient is the client API for SignerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignerService exposes the credential-backed signing operations over gRPC.
// It is designed to run on the host that holds the hardware token or PFX file
// (srvtoken side) and to be called by RemoteSigner running on the pjeheadless
// process.
//
// SECURITY: transport is plain TCP by default, acceptable only on a trusted
// LAN segment or loopback. mTLS hardening is tracked as a backlog item.
// Do NOT expose this service on an untrusted network without TLS.
type SignerServiceClient interface {
	// Sign hashes phrase with the given algorithm and returns a base64-encoded
	// PKCS#1 v1.5 signature.
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignReply, error)
	// CertChainPKIPath returns the ASN.1 PKIPath (SEQUENCE OF Certificate,
	// RFC 3820) of the certificate chain (leaf first), base64-encoded.
	CertChainPKIPath(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Chain, error)
	// Identity returns human-readable metadata from the leaf certificate.
	Identity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityMsg, error)
	// Health probes liveness and readiness without mutating state.
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type signerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerServiceClient(cc grpc.ClientConnInterface) SignerServiceClient {
	return &signerServiceClient{cc}
}

func (c *signerServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignReply)
	err := c.cc.Invoke(ctx, SignerService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) CertChainPKIPath(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Chain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chain)
	err := c.cc.Invoke(ctx, SignerService_CertChainPKIPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) Identity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityMsg)
	err := c.cc.Invoke(ctx, SignerService_Identity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, SignerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServiceServer is the server API for SignerService service.
// All implementations must embed UnimplementedSignerServiceServer
// for forward compatibility.
//
// SignerService exposes the credential-backed signing operations over gRPC.
// It is designed to run on the host that holds the hardware token or PFX file
// (srvtoken side) and to be called by RemoteSigner running on the pjeheadless
// process.
//
// SECURITY: transport is plain TCP by default, acceptable only on a trusted
// LAN segment or loopback. mTLS hardening is tracked as a backlog item.
// Do NOT expose this service on an untrusted network without TLS.
type SignerServiceServer interface {
	// Sign hashes phrase with the given algorithm and returns a base64-encoded
	// PKCS#1 v1.5 signature.
	Sign(context.Context, *SignRequest) (*SignReply, error)
	// CertChainPKIPath returns the ASN.1 PKIPath (SEQUENCE OF Certificate,
	// RFC 3820) of the certificate chain (leaf first), base64-encoded.
	CertChainPKIPath(context.Context, *Empty) (*Chain, error)
	// Identity returns human-readable metadata from the leaf certificate.
	Identity(context.Context, *Empty) (*IdentityMsg, error)
	// Health probes liveness and readiness without mutating state.
	Health(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedSignerServiceServer()
}

// UnimplementedSignerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServiceServer struct{}

func (UnimplementedSignerServiceServer) Sign(context.Context, *SignRequest) (*SignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSignerServiceServer) CertChainPKIPath(context.Context, *Empty) (*Chain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertChainPKIPath not implemented")
}
func (UnimplementedSignerServiceServer) Identity(context.Context, *Empty) (*IdentityMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identity not implemented")
}
func (UnimplementedSignerServiceServer) Health(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSignerServiceServer) mustEmbedUnimplementedSignerServiceServer() {}
func (UnimplementedSignerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServiceServer will
// result in compilation errors.
type UnsafeSignerServiceServer interface {
	mustEmbedUnimplementedSignerServiceServer()
}

func RegisterSignerServiceServer(s grpc.ServiceRegistrar, srv SignerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignerService_ServiceDesc, srv)
}

func _SignerService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_CertChainPKIPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).CertChainPKIPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_CertChainPKIPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).CertChainPKIPath(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_Identity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).Identity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_Identity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).Identity(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SignerService_ServiceDesc is the grpc.ServiceDesc for SignerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signer.SignerService",
	HandlerType: (*SignerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _SignerService_Sign_Handler,
		},
		{
			MethodName: "CertChainPKIPath",
			Handler:    _SignerService_CertChainPKIPath_Handler,
		},
		{
			MethodName: "Identity",
			Handler:    _SignerService_Identity_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SignerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signer.proto",
}
